import json
import os
from datetime import datetime

def generate_html_email(report):
    """
    Generates a premium, responsive HTML email based on the pulse report.
    """
    themes_html = ""
    for theme in report.get('themes', []):
        color = "#2e7d32" if theme.get('sentiment') == "Positive" else "#c62828" if theme.get('sentiment') == "Negative" else "#ef6c00"
        bg_color = "#e8f5e9" if theme.get('sentiment') == "Positive" else "#ffebee" if theme.get('sentiment') == "Negative" else "#fff3e0"
        
        themes_html += f"""
        <div style="background-color: {bg_color}; padding: 15px; border-radius: 8px; border-left: 5px solid {color}; margin-bottom: 15px;">
            <h3 style="margin: 0; color: #333;">{theme['name']}</h3>
            <p style="margin: 5px 0; color: #555;">{theme['description']}</p>
            <div style="font-size: 0.85em; margin-top: 10px;">
                <span style="color: {color}; font-weight: bold; text-transform: uppercase;">{theme['sentiment']}</span>
                <span style="color: #999; margin-left: 10px;">Impact: {theme.get('impact_score', 'N/A')}/10</span>
            </div>
        </div>
        """

    quotes_html = "".join([f'<div style="font-style: italic; color: #666; border-left: 3px solid #ddd; padding-left: 15px; margin: 10px 0;">"{q}"</div>' for q in report.get('top_quotes', [])])
    actions_html = "".join([f'<li style="margin-bottom: 10px; color: #333;">{a}</li>' for a in report.get('action_ideas', [])])

    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GROWW Weekly Pulse</title>
    </head>
    <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f7f6; margin: 0; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.1);">
            <div style="background-color: #00d09c; padding: 30px; text-align: center; color: #ffffff;">
                <h1 style="margin: 0; font-size: 28px;">📈 GROWW Weekly Pulse</h1>
                <p style="margin: 10px 0 0; opacity: 0.9;">{datetime.now().strftime('%B %d, %Y')}</p>
            </div>
            
            <div style="padding: 30px;">
                <p style="color: #333; font-size: 16px; margin-bottom: 25px;">
                    Hi Rushi,<br>
                    Your weekly Groww review pulse is ready, highlighting key user feedback and issues to focus on.
                </p>
                
                <div style="background-color: #f0f7ff; padding: 20px; border-radius: 10px; border: 1px solid #d0e3ff; margin-bottom: 30px;">
                    <h2 style="margin-top: 0; font-size: 18px; color: #0056b3;">📝 Executive Summary</h2>
                    <p style="margin: 0; color: #334d6e; line-height: 1.6;">{report.get('pulse_summary', '')}</p>
                </div>

                <h2 style="border-bottom: 2px solid #eee; padding-bottom: 10px; color: #333;">🎯 Key Growth Themes</h2>
                {themes_html}

                <h2 style="border-bottom: 2px solid #eee; padding-bottom: 10px; color: #333; margin-top: 40px;">💬 Voice of the User</h2>
                {quotes_html}

                <h2 style="border-bottom: 2px solid #eee; padding-bottom: 10px; color: #333; margin-top: 40px;">🚀 Strategic Roadmap</h2>
                <ul style="padding-left: 20px;">
                    {actions_html}
                </ul>
            </div>

            <div style="background-color: #f9f9f9; padding: 20px; text-align: center; color: #999; font-size: 12px; border-top: 1px solid #eee;">
                Generated by GROWW Pulse Engine (Llama-3.3-70B via Groq)
            </div>
        </div>
    </body>
    </html>
    """
    return html_template

if __name__ == "__main__":
    # Example usage: Generate a file for preview
    try:
        with open('../Phase2/pulse_report.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        email_content = generate_html_email(data)
        
        with open('email_draft.html', 'w', encoding='utf-8') as f:
            f.write(email_content)
        
        print("Premium HTML email draft generated: email_draft.html")
    except Exception as e:
        print(f"Error: {e}")
